import type { AnswerDetail, CaptureDetail, QuestionDetail } from "./model";

const time = "2026-08-14T00:00:00Z";
export const testAnswer: AnswerDetail = {
  id: "answer-1",
  answer_key: "synthetic_answer",
  label: "Synthetic answer",
  description: null,
  revision: 1,
  status: "active",
  fill_policy: "auto",
  value_kind: "text",
  value: { kind: "text", value: "Synthetic saved value" },
  choices: [],
  mappings: [],
  events: [],
  verified_at: time,
  created_at: time,
  updated_at: time,
};
export const testQuestion: QuestionDetail = {
  id: "question-1",
  raw_question: "Synthetic question",
  raw_section: "Additional questions",
  raw_help: "Synthetic help",
  site_scope: "linkedin:easy-apply",
  control_kind: "text",
  review_state: "open",
  revision: 1,
  capture_conflict: false,
  current_capture_count: 0,
  option_count: 0,
  seen_count: 2,
  first_seen_at: time,
  last_seen_at: time,
  signature: "synthetic-signature",
  identity_kind: "generic_signature",
  adapter_id: "linkedin",
  adapter_version: "1",
  normalizer_version: 1,
  normalized_question: "synthetic question",
  normalized_section: "additional questions",
  normalized_help: "synthetic help",
  options: [],
  answer: null,
  mapping: null,
  current_captures: [],
  events: [],
};
export const testCapture: CaptureDetail = {
  id: "capture-1",
  question_id: testQuestion.id,
  question_label: testQuestion.raw_question,
  application_context_id: "synthetic-context",
  source: "user_input",
  value_kind: "text",
  value: { kind: "text", value: "Synthetic new value" },
  status: "current",
  revision: 1,
  created_at: time,
  updated_at: time,
  question: testQuestion,
  answer: null,
  mapping: null,
  events: [],
};
